### ISSUE TITLE
move menu page to top-level

### ISSUE THREAD

**Issue by annechinn** [Darrionsjoquist/JimmysFirstOrder#9]
1. create menu.html, menu.css at top-level
2. include styles/shared.css
3. create styles/menu.css and include that in menu.html
3. include scripts/header, footer
4. use images/jimmys-logo instead of one in menutabs
5. remove menutabs directory

**Comment by bOtChuMHATESThEsIklEbUnwiTcH** [comment]
badda big badda boom the problem is no more
